### ISSUE TITLE
    def torch_distributed_zero_first(local_rank: int): 

### ISSUE THREAD

**Issue by tunesh** [tjuskyzhang/yolov4-tiny-tensorrt#7]
I am facing an issue. please help to solve it.
this error is in utils.py in utils

def torch_distributed_zero_first(local_rank: int):
                                                                 ^
SyntaxError: invalid syntax

**Comment by tjuskyzhang** [comment]
> I am facing am issue. please help to solve it.
> this error is in utils.py in utils
> 
> def torch_distributed_zero_first(local_rank: int):
> ^
> SyntaxError: invalid syntax

You can try the master branch of the PyTorch_YOLOv4: git clone -b master https://github.com/WongKinYiu/PyTorch_YOLOv4.git

**Comment by tunesh** [comment]
Thanks, its solved!
